import AppKit

/// Reduces exposure of temporary clipboard writes. These markers are advisory:
/// other local applications can still read the system pasteboard.
public enum ClipboardPrivacy {
    public static let markers = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    @discardableResult public static func writeTemporaryText(_ text: String, to pasteboard: NSPasteboard) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else { return false }
        markTemporary(item)
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        return pasteboard.writeObjects([item])
    }

    public static func markTemporary(_ item: NSPasteboardItem) {
        for type in markers where !item.types.contains(type) { item.setData(Data(), forType: type) }
    }
}
